### ISSUE TITLE
KeyError: 'location'

### ISSUE THREAD

**Issue by yoz2326** [xnaveira/foreman-host-builder#7]
below error:

Hi Xaviera,

I am trying to use your plugin on our Foreman server for multi host deployment, but I get below error when I run it:

 Traceback (most recent call last):
  File "./foreman-host-builder.py", line 194, in <module>
    main(sys.argv[1:])
  File "./foreman-host-builder.py", line 86, in main
    build_dict['location_id'] = _ugly_id_lookup(foreman_api, servers[server]['location'],'locations')
KeyError: 'location'

Is there anything in particular I should pay attention to before using the plugin ?
Default Python version running on the host is 2.7

As a side note, I'm looking to use Foreman and foreman-host-builder plugin for AWS deployments. 

Regards,
Ionut.

**Comment by romdav00** [comment]
The same for me...

**Comment by romdav00** [comment]
Ok, the pb was the first line in YAML sample (servers:) that needs to be commented.
